### ISSUE TITLE
I encountered a problem creating the bot here showing an error

### ISSUE THREAD

**Issue by AliAdnanc7** [rvaidun/cheggbot#2]
------------------------------------------------------------------------
{'appId': 'PXaOtQIWNf', 'jsClientSrc': '/aOtQIWNf/init.js', 'firstPartyEnabled': True, 'uuid': '97c39380-c2b8-11eb-a496-65c644533924', 'hostUrl': '/aOtQIWNf/xhr', 'blockScript': '/aOtQIWNf/captcha/captcha.js?a=c&u=97c39380-c2b8-11eb-a496-65c644533924&v=&m=0'}
Traceback (most recent call last):
  File "c.py", line 36, in <module>
    acc = CheggAccount(setup['CheggEmail'], setup['CheggPassword'])
  File "/home/ali/سطح المكتب/مشاريع/bot-telegram/New/telegrambot/ملفات البرمجه هيروكو/تجارب/بايثون  api تطبيق/cheggbot/chegg.py", line 11, in __init__
    if (self.login(username, password) == False):
  File "/home/ali/سطح المكتب/مشاريع/bot-telegram/New/telegrambot/ملفات البرمجه هيروكو/تجارب/بايثون  api تطبيق/cheggbot/chegg.py", line 79, in login
    if j['mfaChallengeDetails'] != None:
KeyError: 'mfaChallengeDetails'

**Comment by rvaidun** [comment]
This error usually means that your IP address has been flagged by Chegg and Chegg is blocking your IP from accessing their API. This can occur if you are using a VPN/proxy or if you send too many requests to their API. Hope this helps.
