### ISSUE TITLE
Error while reading some characters from some specific questions

### ISSUE THREAD

**Issue by Half-Note** [rvaidun/cheggbot#4]
Traceback (most recent call last):
  File "C:\Users\Fahad\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Fahad\Desktop\Chegg Solution\cheggbot-main\bot.py", line 91, in chegg
    answer = await cheggURL(url, ctx.message)
  File "C:\Users\Fahad\Desktop\Chegg Solution\cheggbot-main\bot.py", line 40, in cheggURL
    answer = acc.get_question_info(url)
  File "C:\Users\Fahad\Desktop\Chegg Solution\cheggbot-main\chegg.py", line 18, in wrapper_do_twice
    return func(self, *args, **kwargs)
  File "C:\Users\Fahad\Desktop\Chegg Solution\cheggbot-main\chegg.py", line 123, in get_question_info
    f.write(page.text)
  File "C:\Users\Fahad\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0412' in position 155693: character maps to <undefined>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Fahad\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Fahad\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\Fahad\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: UnicodeEncodeError: 'charmap' codec can't encode character '\u0412' in position 155693: character maps to <undefined>

**Comment by Half-Note** [comment]
with open("random.html", "w" ,encoding="utf-8") as f: // tried this one got it resolved in chegg.py file

**Comment by rvaidun** [comment]
Fixed. random.html not needed.
